// === TRANSLATIONS ===
export const translations = {
    ro: {
        'dashboard-title': 'Dashboard - 25 Mai 2025',
        'refresh': 'Refresh',
        'quick-actions': 'Acțiuni Rapide',
        'language-romanian': 'Română',
        'language-english': 'English',
        'language-italian': 'Italiano',
        'language-spanish': 'Español',
        'total-active-agents': 'Total Agenți Activi',
        'planned-hours': 'Ore Planificate',
        'average-productivity': 'Productivitate Medie',
        'last-7-days': 'Ultimele 7 zile',
        'today': 'Azi',
        'tomorrow': 'Mâine',
        'for-agents': 'Pentru 42 agenți',
        'hours-by-team': 'Ore Alocate pe Echipe - Azi',
        'shop': 'Shop',
        'agents': 'Agenți',
        'total-hours': 'Total Ore',
        'productivity-trend': 'Trend Productivitate - Ultimele 30 Zile',
        'users-title': 'Gestionare Utilizatori',
        'add-new-user': 'Adaugă Utilizator Nou',
        'full-name': 'Nume Complet',
        'username': 'Nume Utilizator',
        'contract-hours': 'Ore Contract',
        'contract-type': 'Tip Contract',
        'primary-team': 'Echipa Principală',
        'hire-date': 'Data Angajării',
        'active': 'Activ',
        'actions': 'Acțiuni',
        'delete': 'Șterge'
    },
    en: {
        'dashboard-title': 'Dashboard - May 25, 2025',
        'refresh': 'Refresh',
        'quick-actions': 'Quick Actions',
        'language-romanian': 'Romanian',
        'language-english': 'English',
        'language-italian': 'Italian',
        'language-spanish': 'Spanish',
        'total-active-agents': 'Total Active Agents',
        'planned-hours': 'Planned Hours',
        'average-productivity': 'Average Productivity',
        'last-7-days': 'Last 7 days',
        'today': 'Today',
        'tomorrow': 'Tomorrow',
        'for-agents': 'For 42 agents',
        'hours-by-team': 'Hours by Team',
        'shop': 'Shop',
        'agents': 'Agents',
        'total-hours': 'Total Hours',
        'productivity-trend': 'Productivity Trend - Last 30 Days',
        'users-title': 'Users Management',
        'add-new-user': 'Add New User',
        'full-name': 'Full Name',
        'username': 'Username',
        'contract-hours': 'Contract Hours',
        'contract-type': 'Contract Type',
        'primary-team': 'Primary Team',
        'hire-date': 'Hire Date',
        'active': 'Active',
        'actions': 'Actions',
        'delete': 'Delete'
    },
    it: {
        'dashboard-title': 'Pannello di Controllo',
        'refresh': 'Aggiorna',
        'quick-actions': 'Azioni Rapide',
        'language-romanian': 'Rumeno',
        'language-english': 'Inglese',
        'language-italian': 'Italiano',
        'language-spanish': 'Spagnolo',
        'total-active-agents': 'Agenti Attivi Totali',
        'planned-hours': 'Ore Pianificate',
        'average-productivity': 'Produttività Media',
        'last-7-days': 'Ultimi 7 giorni',
        'today': 'Oggi',
        'tomorrow': 'Domani',
        'for-agents': 'Per 42 agenti',
        'hours-by-team': 'Ore per Team',
        'shop': 'Shop',
        'agents': 'Agenti',
        'total-hours': 'Ore Totali',
        'productivity-trend': 'Trend di Produttività - Ultimi 30 Giorni',
        'users-title': 'Gestione Utenti',
        'add-new-user': 'Aggiungi Nuovo Utente',
        'full-name': 'Nome Completo',
        'username': 'Nome Utente',
        'contract-hours': 'Ore di Contratto',
        'contract-type': 'Tipo di Contratto',
        'primary-team': 'Team Principale',
        'hire-date': 'Data di Assunzione',
        'active': 'Attivo',
        'actions': 'Azioni',
        'delete': 'Elimina'
    },
    es: {
        'dashboard-title': 'Panel de Control',
        'refresh': 'Actualizar',
        'quick-actions': 'Acciones Rápidas',
        'language-romanian': 'Rumano',
        'language-english': 'Inglés',
        'language-italian': 'Italiano',
        'language-spanish': 'Español',
        'total-active-agents': 'Total Agentes Activos',
        'planned-hours': 'Horas Planificadas',
        'average-productivity': 'Productividad Promedio',
        'last-7-days': 'Últimos 7 días',
        'today': 'Hoy',
        'tomorrow': 'Mañana',
        'for-agents': 'Para 42 agentes',
        'hours-by-team': 'Horas por Equipo',
        'shop': 'Shop',
        'agents': 'Agentes',
        'total-hours': 'Horas Totales',
        'productivity-trend': 'Tendencia de Productividad - Últimos 30 Días',
        'users-title': 'Gestión de Usuarios',
        'add-new-user': 'Añadir Nuevo Usuario',
        'full-name': 'Nombre Completo',
        'username': 'Nombre de Usuario',
        'contract-hours': 'Horas de Contrato',
        'contract-type': 'Tipo de Contrato',
        'primary-team': 'Equipo Principal',
        'hire-date': 'Fecha de Contratación',
        'active': 'Activo',
        'actions': 'Acciones',
        'delete': 'Eliminar'
    }
};

// Charts colors configuration
export const chartColors = {
    primary: '#ffd700',
    secondary: '#b8bbd8',
    grid: '#2a3f5f',
    text: '#b8bbd8',
    teams: {
        'RO zooplus': '#ffd700',  // Gold
        'HU zooplus': '#4caf50',  // Green
        'IT zooplus': '#2196f3',  // Blue
        'NL zooplus': '#ff9800',  // Orange
        'DE zooplus': '#9c27b0'   // Purple
    }
};

// Language configuration
export const languageConfig = {
    ro: { flag: '🇷🇴', name: 'Română' },
    en: { flag: '🇺🇸', name: 'English' },
    it: { flag: '🇮🇹', name: 'Italiano' },
    es: { flag: '🇪🇸', name: 'Español' }
}; 