// === TRANSLATIONS ===
export const translations = {
    ro: {
        // Dashboard
        'dashboard-title': 'Dashboard',
        'total-active-agents': 'Total Agenți Activi',
        'agents-in-db': 'Agenți în baza de date*',
        'planned-hours': 'Ore Planificate',
        'agents-planned': 'agenți planificați',
        'average-productivity': 'Productivitate Medie',
        'today': 'Azi',
        'tomorrow': 'Mâine',
        'hours-by-team': 'Ore Alocate pe Echipe',
        'hours-by-team-today': 'Ore Alocate pe Echipe - Azi',
        'hours-by-team-tomorrow': 'Ore Alocate pe Echipe - Mâine',
        'shop': 'Shop',
        'agents': 'Agenți',
        'total-hours': 'Total Ore',
        'productivity-trend': 'Trend Productivitate - Ultimele 30 Zile',

        // Users
        'users-title': 'Gestionare Utilizatori',
        'add-new-user': 'Adaugă Utilizator Nou',
        'full-name': 'Nume Complet',
        'username': 'Nume Utilizator',
        'contract-hours': 'Ore Contract',
        'contract-type': 'Tip Contract',
        'primary-team': 'Echipa Principală',
        'hire-date': 'Data Angajării',
        'active': 'Activ',
        'inactive': 'Inactiv',
        'actions': 'Acțiuni',
        'delete': 'Șterge',
        'contract-change-to-pt': 'Schimbare la Part-time',
        'contract-change-to-ft': 'Schimbare la Full-time',
        'select-start-date': 'Selectează data de începere.',
        'date-must-be-current-month': 'Data trebuie să fie în luna curentă.',
        'select-start-date-deact': 'Selectează data de început.',
        'end-date-after-start': 'Data de sfârșit trebuie să fie după data de început.',
        'connecting': 'Se conectează...',
        'login-google': 'Conectează-te cu Google',
        'auth-popup-closed': 'Fereastra de autentificare a fost închisă.',
        'auth-popup-blocked': 'Fereastra popup a fost blocată. Permite popup-urile pentru acest site.',
        'auth-cancelled': 'Cererea de autentificare a fost anulată.',
        'auth-network-error': 'Eroare de rețea. Verifică conexiunea la internet.',
        'auth-unauthorized-domain': 'Domeniul nu este autorizat. Contactează administratorul.',
        'auth-generic-error': 'Eroare la autentificare. Încearcă din nou.',

        // Planner
        'planner-title': 'Planificator',
        'search-agent-placeholder': 'Caută agent...',
        'select-agents': 'Caută & Selectează',

        // Productivity
        'productivity-title': 'Productivitate',
        'prod-agents-processed': 'Agenți Procesați',
        'prod-tickets-resolved': 'Tickete Rezolvate',
        'prod-calls-answered': 'Apeluri Răspunse',
        'prod-average': 'Productivitate Medie',
        'prod-from-xlsx': 'din fișiere XLSX',
        'prod-from-csv': 'din fișiere CSV',
        'prod-formula': '(tickete+apeluri) / ore',
        'prod-days': 'zile',
        'prod-day': 'zi',
        'prod-with-data': 'cu date',
        'prod-no-agents': 'Niciun agent găsit. Verifică dacă perioada selectată conține date încărcate și dacă agenții sunt înregistrați.',
        'prod-upload-to-see': 'Încarcă fișierele din secțiunea Upload pentru a vedea datele.',
        'prod-select-agent': 'Selectează cel puțin un agent din lista de mai sus.',
        'prod-no-results': 'Niciun rezultat pentru selecția curentă.',
        'prod-all-teams': 'Toate',
        'prod-summary': 'Sumar',
        'prod-per-agent': 'Per Agent',
        'prod-all-btn': 'Toți',
        'prod-none-btn': 'Niciunul',
        'prod-selected': 'selectați',
        'prod-agents-from-tickets': 'agenți din tickete',
        'prod-agents-from-calls': 'agenți din apeluri',
        'prod-agents-tickets': 'agenți tickete',
        'prod-agents-calls': 'agenți apeluri',
        'prod-no-data-tooltip': 'fără date',
        'prod-data-uploaded-for': 'Date încărcate pentru',
        'prod-can-add-file': 'Poți adăuga și celălalt fișier sau schimba data.',
        'prod-date-selected': 'Data selectată:',
        'prod-can-upload': 'poți încărca fișierele.',
        'prod-data-exists': 'există deja. Încărcarea de fișiere noi va suprascrie datele existente pentru această zi.',
        'prod-data-for': 'Datele pentru',
        'prod-select-period': 'Selectează perioada...',
        'prod-search-agent': 'Caută agent...',
        'prod-save-error': 'Eroare la salvarea datelor în baza de date.',
        'prod-delete-btn': 'Șterge datele pentru această zi',
        'prod-deleted': 'Datele pentru {date} au fost șterse.',
        'prod-select-date-first': 'Selectează mai întâi data fișierelor!',
        'prod-agents-selected': 'Agenți Selectați',
        'prod-total-tickets': 'Total Tickete',
        'prod-total-calls': 'Total Apeluri',
        'prod-days-with-data': 'zile cu date',

        // Table headers
        'th-agent': 'Agent',
        'th-teams': 'Echipe',
        'th-tickets': 'Tickete',
        'th-calls': 'Apeluri',
        'th-total': 'Total',
        'th-hours-worked': 'Ore Lucrate',
        'th-productivity': 'Productivitate',
        'th-date': 'Data',
        'th-schedule': 'Program',
        'th-hours': 'Ore',

        // Planner
        'planner-agent': 'Agent',
        'planner-hours': 'Ore',
        'planner-total': 'Total',
        'planner-week-total': 'Total Săpt.',
        'planner-day-names': 'DUM,LUN,MAR,MIE,JOI,VIN,SÂM',
        'planner-search-team': 'Caută echipă...',
        'planner-search-agent': 'Caută agent...',
        'planner-select-months': 'Selectați una sau mai multe luni pentru a le vizualiza.',
        'planner-invalid-range': 'Perioadă invalidă.',
        'planner-rotate': 'Rotește telefonul în mod landscape pentru a folosi Planificatorul',
        'edit-btn': 'Editează',

        // Reports
        'reports-hours-per-shop': 'Ore Planificate per Shop',
        'reports-distribution': 'Distribuție Agenți per Shop',
        'reports-shop': 'Shop',
        'reports-total-hours': 'Total Ore',
        'reports-nr-agents': 'Nr. Agenți',
        'reports-agents-hours': 'agenți',
        'reports-hours-unit': 'ore',
        'reports-select-range': 'Selectează un interval de date pentru a genera rapoartele.',
        'reports-no-data': 'Nu există date planificate pentru intervalul selectat.',

        // Charts
        'charts-no-data': 'Nu există date de productivitate încărcate. Încarcă fișiere din secțiunea Upload.',
        'charts-hours-unit': 'ore',

        // Edit Modal
        'edit-title': 'Editează Selecția',
        'edit-current-selection': 'Selecție Curentă',
        'edit-type-title': 'Tipul de Editare',
        'edit-working-hours': 'Ore de Lucru',
        'edit-working-desc': 'Modifică alocarea orelor pe echipe (ex: 6 IT + 2 HU)',
        'edit-holiday': 'Concediu (CO)',
        'edit-holiday-desc': 'Marchează zilele ca fiind concediu',
        'edit-sick': 'Concediu Medical (CM)',
        'edit-sick-desc': 'Marchează zilele ca fiind concediu medical',
        'edit-dayoff': 'Zi Liberă (LB)',
        'edit-dayoff-desc': 'Marchează ca zi liberă cu justificare obligatorie',
        'edit-legal-holiday': 'Sărbătoare Legală (SL)',
        'edit-legal-holiday-desc': 'Marchează zilele ca sărbătoare legală',
        'edit-maternity': 'Concediu Maternitate (MA)',
        'edit-maternity-desc': 'Marchează zilele ca concediu de maternitate',
        'edit-donation': 'Donare de Sânge (DO)',
        'edit-donation-desc': 'Marchează zilele pentru donare de sânge',
        'edit-bereavement': 'Deces (DC)',
        'edit-bereavement-desc': 'Marchează zilele pentru eveniment de deces',
        'edit-note-title': 'Notițe / Motiv',
        'edit-note-placeholder': 'Adaugă o notiță sau motiv (opțional)...',
        'edit-config-hours': 'Configurare Ore de Lucru',
        'edit-total': 'Total:',
        'edit-hours-unit': 'ore',
        'edit-over-limit': 'Depășește limita de 12 ore',
        'edit-dayoff-reason': 'Justificare pentru Zi Liberă',
        'edit-dayoff-placeholder': 'Introdu motivul pentru ziua liberă (obligatoriu)...',
        'edit-cancel': 'Anulează',
        'edit-save': 'Salvează Modificările',
        'edit-select-cells': 'Selectează cel puțin o celulă pentru editare.',
        'edit-select-type': 'Selectează un tip de modificare.',
        'edit-over-12': 'Totalul orelor nu poate depăși 12 ore pe zi.',
        'edit-selection': 'Selecție:',
        'edit-cells-selected': 'celule selectate',
        'edit-total-hours': 'Total ore:',
        'undo-button': 'Anulează',
        'undo-nothing': 'Nu există modificări de anulat.',
        'undo-confirm': 'Ești sigur că vrei să anulezi ultima modificare?',
        'undo-success': 'Modificările au fost anulate!',
        'deactivate-start': 'Data de început',
        'deactivate-end': 'Data de sfârșit (opțional)',
        'deactivate-end-hint': 'Lasă data de sfârșit goală pentru dezactivare indefinită',
        'deactivate-notes': 'Motiv dezactivare',
        'deactivate-notes-placeholder': 'Introdu motivul dezactivării (opțional)...',
        'deactivate-apply': 'Aplică',

        // Upload
        'upload-title': 'Încărcare Fișiere',
        'select-date': '1. Selectează data fișierelor',
        'date-question': 'Pentru ce zi sunt datele de productivitate?',
        'tickets-xlsx': '2. Tickete (XLSX)',
        'calls-csv': '3. Apeluri (CSV)',
        'drag-xlsx': 'Trage fișierul Excel aici sau click pentru selectare',
        'drag-csv': 'Trage fișierul CSV aici sau click pentru selectare',
        'uploaded-data': 'Date Încărcate',

        // Reports
        'reports-title': 'Rapoarte',

        // Info
        'info-title': 'Informații',
        'info-dashboard-title': '1. Dashboard',
        'info-dashboard-desc': 'Pagina principală oferă o vedere de ansamblu a echipei:',
        'info-dashboard-agents': 'Total Agenți Activi — numărul de agenți înregistrați și activi în sistem',
        'info-dashboard-hours': 'Ore Planificate — totalul orelor planificate pentru ziua curentă (Azi) sau orice dată selectată din calendar',
        'info-dashboard-teams': 'Ore Alocate pe Echipe — tabelul arată distribuția orelor pe echipe pentru data selectată',
        'info-dashboard-prod': 'Productivitate Medie — media productivității (tickete+apeluri / oră) pe ultimele zile cu date încărcate',
        'info-dashboard-trend': 'Trend Productivitate — graficul arată productivitatea per echipă (tickete+apeluri / oră) pe toată luna curentă',
        'info-users-title': '2. Users (Utilizatori)',
        'info-users-desc': 'Gestionarea agenților din echipă:',
        'info-users-add': 'Adaugă agent nou — completează numele, username-ul, orele de contract, tipul contractului, echipa primară și data angajării',
        'info-users-inline': 'Editare inline — click direct pe orice câmp din tabel pentru a-l modifica (numele, orele, echipa etc.)',
        'info-users-team': 'Echipa primară — echipa principală a agentului (ex: RO zooplus). Agentul poate lucra și pentru alte echipe conform plannerului',
        'info-users-contract': 'Tip Contract — Full-time (8h automat) sau Part-time (ore configurabile). Schimbarea tipului de contract deschide un modal pentru a selecta data de start și noile ore',
        'info-users-active': 'Activ/Inactiv — buton care deschide un modal cu opțiuni: Indefinit (dezactivare permanentă) sau Perioadă (interval de date). Plannerul se actualizează automat',
        'info-planner-title': '3. Planner',
        'info-planner-desc': 'Planificarea lunară a orelor de lucru per agent:',
        'info-planner-format': 'Format ore — introdu orele cu codul echipei: 8RO = 8 ore pe RO, 4RO+4IT = 4 ore RO + 4 ore IT',
        'info-planner-codes': 'Coduri speciale — Co = Concediu, CM = Concediu Medical, SL = Sărbătoare Legală, LB = Liber',
        'info-planner-multi': 'Selecție multiplă — selectează mai multe celule și editează-le simultan cu modalul de editare',
        'info-planner-auto': 'Salvare automată — toate modificările se salvează automat în baza de date',
        'info-prod-title': '4. Productivitate',
        'info-prod-desc': 'Analiza productivității bazată pe datele încărcate (tickete + apeluri) și orele din planner:',
        'info-prod-period': 'Selectare perioadă — alege un interval de date cu calendarul din colțul dreapta-sus',
        'info-prod-filter': 'Filtru echipă — selectează o echipă specifică (ex: RO, IT) pentru a vedea doar ticketele și apelurile rezolvate pentru acea echipă',
        'info-prod-summary': 'Sumar — vedere agregată per agent pe întreaga perioadă selectată',
        'info-prod-agent': 'Per Agent — vedere detaliată zi cu zi, per agent. Selectează agenții folosind chipurile sau căutarea',
        'info-prod-teams': 'Echipe (coloana) — arată echipele pentru care agentul a lucrat efectiv, bazat pe fișierele încărcate',
        'info-prod-formula': 'Formula — Productivitate = (Tickete + Apeluri) / Ore Lucrate',
        'info-upload-title': '5. Upload File',
        'info-upload-desc': 'Încărcarea fișierelor de productivitate zilnică:',
        'info-upload-step1': 'Pasul 1: Selectează data — alege data din calendar pentru care încarci datele. Sistemul avertizează dacă data are deja date încărcate',
        'info-upload-step2': 'Pasul 2: Fișier XLSX (Tickete) — încarcă fișierul Excel cu ticketele rezolvate. Sistemul extrage automat agentul, numărul de tickete și echipa',
        'info-upload-step3': 'Pasul 3: Fișier CSV (Apeluri) — încarcă fișierul CSV cu apelurile. Sistemul extrage agentul, numărul de apeluri și echipa',
        'info-upload-match': 'Potrivire automată — numele din fișiere sunt normalizate și potrivite automat cu agenții din sistem',
        'info-upload-persist': 'Persistență — datele sunt salvate în Firebase și se păstrează între sesiuni',
        'info-reports-title': '6. Rapoarte',
        'info-reports-desc': 'Rapoarte agregate bazate pe datele din planner:',
        'info-reports-range': 'Selectare interval — alege perioada dorită cu calendarul (default: luna curentă)',
        'info-reports-shop': 'Ore Planificate per Shop — tabel cu totalul orelor planificate pe fiecare echipă și numărul de agenți',
        'info-reports-dist': 'Distribuție Agenți per Shop — carduri per echipă cu fiecare agent și orele lui, ordonate descrescător',
        'info-ai-title': '7. Sherpa AI',
        'info-ai-desc': 'Asistent AI integrat care poate răspunde la întrebări și efectua acțiuni:',
        'info-ai-ask': 'Întrebări — întreabă orice despre planificarea echipei, orele lucrate, productivitatea, sau distribuția pe echipe',
        'info-ai-actions': 'Acțiuni — Sherpa AI poate modifica planificarea, adăuga sau șterge agenți, și naviga între pagini',
        'info-ai-safety': 'Siguranță — acțiunile destructive (ștergere) necesită confirmare. Modificările sunt limitate și validate automat',
        'info-ai-lang': 'Multilingv — răspunde în limba selectată (Română, Engleză, Italiană)',
        'info-teams-title': 'Coduri Echipe',
        'info-team-ro': 'România',
        'info-team-hu': 'Ungaria',
        'info-team-it': 'Italia',
        'info-team-nl': 'Olanda',
        'info-team-cs': 'Cehia',
        'info-team-sk': 'Slovacia',
        'info-team-se': 'Suedia',
        'info-team-de': 'Germania',

        // Login
        'login-button': 'Conectează-te cu Google',
        'logout': 'Deconectare',

        // Language names
        'language-romanian': 'Română',
        'language-english': 'English',
        'language-italian': 'Italiano',

        // Chat
        'chat-welcome': 'Salut! Sunt Sherpa AI. Întreabă-mă orice despre planificarea echipei sau cere-mi să fac modificări.',
        'chat-error': 'Eroare la comunicarea cu AI. Încearcă din nou.',
        'chat-invalid-key': 'Cheia API este invalidă. Verifică setările.',
        'chat-rate-limit': 'Prea multe cereri. Așteaptă câteva secunde.',
        'chat-delete-cancelled': 'Ștergerea a fost anulată.',

        // Nav items
        'nav-dashboard': 'Dashboard',
        'nav-users': 'Utilizatori',
        'nav-planner': 'Planificator',
        'nav-productivity': 'Productivitate',
        'nav-upload': 'Încărcare Fișiere',
        'nav-reports': 'Rapoarte',
        'nav-logs': 'Jurnal',
        'nav-roadmap': 'Roadmap',
        'nav-info': 'Informații',

        // Logs
        'logs-title': 'Jurnal Activitate',
        'logs-loading': 'Se încarcă...',
        'logs-empty': 'Nu există activitate înregistrată.',
        'logs-time': 'Ora',
        'logs-user': 'Utilizator',
        'logs-type': 'Tip',
        'logs-action': 'Acțiune',
        'logs-details': 'Detalii',
        'logs-filter-all': 'Toate',
        'logs-refresh': 'Reîncarcă',

        // Roadmap
        'roadmap-title': 'Roadmap',
        'roadmap-bugs-title': 'Bugs Cunoscute',
        'roadmap-findings-title': 'Constatări & Îmbunătățiri Recomandate',
        'roadmap-future-title': 'Dezvoltări Viitoare',
        'roadmap-bug-1': 'Gemini API returnează 404 pe unele browsere din cauza cache-ului — necesită Ctrl+Shift+R',
        'roadmap-bug-2': 'Rata de cereri API limitată fără profil de facturare Google configurat',
        'roadmap-bug-3': 'Cross-Origin-Opener-Policy blochează popup-ul de login pe unele browsere',
        'roadmap-bug-4': 'Gemini 3.x „thinking mode" activ implicit provoacă eroare 400 cu function calling — Rezolvat',
        'roadmap-bug-5': 'Function response trimis ca array în loc de obiect — eroare proto serialization — Rezolvat',
        'roadmap-bug-6': 'Acțiunile de editare din planner nu sunt înregistrate în jurnal — Rezolvat',
        'roadmap-finding-1': 'Accesibilitate — lipsesc atribute ARIA, navigare cu tastatura, contrast insuficient pe text secundar',
        'roadmap-finding-2': 'Performanță — tabelul planner-ului generează 2000+ noduri DOM; ar beneficia de virtualizare',
        'roadmap-finding-3': 'Securitate — cheia Gemini API este expusă client-side; ar trebui proxy prin Cloud Functions',
        'roadmap-finding-4': 'Stări de încărcare — lipsesc spinners/skeletons la încărcarea datelor din Firestore',
        'roadmap-finding-5': 'Validare date — lipsește validare de schemă la scrierea în Firestore',
        'roadmap-finding-6': 'Istoric chat — se pierde la reîncărcarea paginii (doar în memorie)',
        'roadmap-finding-7': 'AI primea toate datele în prompt (10KB+) — migrat la Gemini function calling — Implementat',
        'roadmap-finding-8': 'Vulnerabilitate XSS în renderizarea mesajelor chat — Rezolvat',
        'roadmap-finding-9': 'AI putea șterge agenți fără confirmare utilizator — Adăugat gate de confirmare',
        'roadmap-future-1': 'Persistența istoricului chat în localStorage',
        'roadmap-future-2': 'Export rapoarte în PDF / Excel',
        'roadmap-future-3': 'Notificări push pentru schimbări de program',
        'roadmap-future-4': 'Roluri utilizator (admin, manager, vizualizare)',
        'roadmap-future-5': 'Dashboard cu grafice interactive (drag-and-drop pe planner)',
        'roadmap-future-6': 'Integrare calendar (Google Calendar sync)',
        'roadmap-future-7': 'Mod offline cu sincronizare la reconectare',
        'roadmap-future-8': 'Audit trail complet cu revert la versiuni anterioare — Implementat',
        'roadmap-future-9': 'Logare acțiuni planner (editare celule, creare/ștergere agenți) în jurnal',
        'roadmap-future-10': 'Proxy API key prin Cloud Functions pentru securitate',
        'roadmap-future-11': 'Point-in-Time Restore — salvare automată a snapshot-urilor plannerului în Firestore, cu posibilitatea de a restaura starea echipei la orice moment din trecut',

        // Form & UI strings
        'create-user-title': 'Creează un Profil Nou',
        'form-name-placeholder': 'ex: Ion Popescu',
        'form-username-placeholder': 'ex: ion.popescu',
        'form-pt-hours': 'Ore Part-time',
        'form-4h': '4 ore/zi',
        'form-5h': '5 ore/zi',
        'form-6h': '6 ore/zi',
        'form-7h': '7 ore/zi',
        'form-8h': '8 ore/zi',
        'form-full-time': 'Full-time',
        'form-part-time': 'Part-time',
        'form-create-user': 'Creează Utilizator',
        'filter-agent': 'Agent',
        'filter-team': 'Echipă',
        'filter-clear': 'Șterge Selecțiile',
        'no-hours-planned': 'Nu sunt ore planificate pentru această dată.',
        'avg-prod-last-days': 'Ultimele {n} zile cu date',
        'avg-prod-no-data': 'Nicio dată de productivitate',
        'error-loading-users': 'Eroare la încărcarea utilizatorilor.',
        'confirm-delete-user': 'Ești sigur că vrei să ștergi {name}?',
        'fill-required-fields': 'Completează toate câmpurile obligatorii.',
        'pt-hours-range': 'Orele part-time trebuie să fie între 4 și 7.',
        'user-created': '{name} creat cu program {hours}h/{team}.',
        'reactivation-title': 'Reactivare',
        'reactivate-btn': 'Reactivează',
        'agent-reactivated': '{name} a fost reactivat.',
        'deactivation-title': 'Dezactivare',
        'agent-deactivated': '{name} dezactivat: {from} — {to}',
        'contract-updated': 'Contract {name} actualizat: {type} ({hours}h) din {date}',
        'hours-range-error': 'Orele de contract trebuie să fie între 4 și 8.',
        'hire-date-empty': 'Data de angajare nu poate fi goală.',
        'user-updated': 'Utilizator actualizat.',
        'name-empty': 'Numele nu poate fi gol.',
        'confirm-delete-agent': 'Ești sigur că vrei să ștergi acest agent?',
        'unknown-agent': 'Agent Necunoscut',
        'error-file-processing': 'Eroare: {name}',
        'data-overwritten': '"{name}" — datele pentru {date} au fost suprascrise.',
        'file-processed': '"{name}" procesat pentru {date}!',
        'error-generic': 'Eroare: {msg}',
    },
    en: {
        // Dashboard
        'dashboard-title': 'Dashboard',
        'total-active-agents': 'Total Active Agents',
        'agents-in-db': 'Agents in database*',
        'planned-hours': 'Planned Hours',
        'agents-planned': 'agents planned',
        'average-productivity': 'Average Productivity',
        'today': 'Today',
        'tomorrow': 'Tomorrow',
        'hours-by-team': 'Hours Allocated by Team',
        'hours-by-team-today': 'Hours Allocated by Team - Today',
        'hours-by-team-tomorrow': 'Hours Allocated by Team - Tomorrow',
        'shop': 'Shop',
        'agents': 'Agents',
        'total-hours': 'Total Hours',
        'productivity-trend': 'Productivity Trend',

        // Users
        'users-title': 'User Management',
        'add-new-user': 'Add New User',
        'full-name': 'Full Name',
        'username': 'Username',
        'contract-hours': 'Contract Hours',
        'contract-type': 'Contract Type',
        'primary-team': 'Primary Team',
        'hire-date': 'Hire Date',
        'active': 'Active',
        'inactive': 'Inactive',
        'actions': 'Actions',
        'delete': 'Delete',
        'contract-change-to-pt': 'Change to Part-time',
        'contract-change-to-ft': 'Change to Full-time',
        'select-start-date': 'Please select a start date.',
        'date-must-be-current-month': 'The date must be in the current month.',
        'select-start-date-deact': 'Please select a start date.',
        'end-date-after-start': 'End date must be after the start date.',
        'connecting': 'Connecting...',
        'login-google': 'Sign in with Google',
        'auth-popup-closed': 'The authentication window was closed.',
        'auth-popup-blocked': 'The popup was blocked. Please allow popups for this site.',
        'auth-cancelled': 'The authentication request was cancelled.',
        'auth-network-error': 'Network error. Please check your internet connection.',
        'auth-unauthorized-domain': 'Domain not authorized. Contact the administrator.',
        'auth-generic-error': 'Authentication error. Please try again.',

        // Planner
        'planner-title': 'Planner',
        'search-agent-placeholder': 'Search agent...',
        'select-agents': 'Search & Select',

        // Productivity
        'productivity-title': 'Productivity',
        'prod-agents-processed': 'Agents Processed',
        'prod-tickets-resolved': 'Tickets Resolved',
        'prod-calls-answered': 'Calls Answered',
        'prod-average': 'Average Productivity',
        'prod-from-xlsx': 'from XLSX files',
        'prod-from-csv': 'from CSV files',
        'prod-formula': '(tickets+calls) / hours',
        'prod-days': 'days',
        'prod-day': 'day',
        'prod-with-data': 'with data',
        'prod-no-agents': 'No agent found. Check if the selected period contains uploaded data and if agents are registered.',
        'prod-upload-to-see': 'Upload files from the Upload section to see the data.',
        'prod-select-agent': 'Select at least one agent from the list above.',
        'prod-no-results': 'No results for the current selection.',
        'prod-all-teams': 'All',
        'prod-summary': 'Summary',
        'prod-per-agent': 'Per Agent',
        'prod-all-btn': 'All',
        'prod-none-btn': 'None',
        'prod-selected': 'selected',
        'prod-agents-from-tickets': 'agents from tickets',
        'prod-agents-from-calls': 'agents from calls',
        'prod-agents-tickets': 'agents tickets',
        'prod-agents-calls': 'agents calls',
        'prod-no-data-tooltip': 'no data',
        'prod-data-uploaded-for': 'Data uploaded for',
        'prod-can-add-file': 'You can add another file or change the date.',
        'prod-date-selected': 'Selected date:',
        'prod-can-upload': 'you can upload the files.',
        'prod-data-exists': 'already exists. Uploading new files will overwrite the existing data for this day.',
        'prod-data-for': 'Data for',
        'prod-select-period': 'Select period...',
        'prod-search-agent': 'Search agent...',
        'prod-save-error': 'Error saving data to database.',
        'prod-delete-btn': 'Delete data for this day',
        'prod-deleted': 'Data for {date} has been deleted.',
        'prod-select-date-first': 'Select the file date first!',
        'prod-agents-selected': 'Agents Selected',
        'prod-total-tickets': 'Total Tickets',
        'prod-total-calls': 'Total Calls',
        'prod-days-with-data': 'days with data',

        // Table headers
        'th-agent': 'Agent',
        'th-teams': 'Teams',
        'th-tickets': 'Tickets',
        'th-calls': 'Calls',
        'th-total': 'Total',
        'th-hours-worked': 'Hours Worked',
        'th-productivity': 'Productivity',
        'th-date': 'Date',
        'th-schedule': 'Schedule',
        'th-hours': 'Hours',

        // Planner
        'planner-agent': 'Agent',
        'planner-hours': 'Hours',
        'planner-total': 'Total',
        'planner-week-total': 'Week Total',
        'planner-day-names': 'SUN,MON,TUE,WED,THU,FRI,SAT',
        'planner-search-team': 'Search team...',
        'planner-search-agent': 'Search agent...',
        'planner-select-months': 'Select one or more months to view.',
        'planner-invalid-range': 'Invalid period.',
        'planner-rotate': 'Rotate your phone to landscape to use the Planner',
        'edit-btn': 'Edit',

        // Reports
        'reports-hours-per-shop': 'Planned Hours per Shop',
        'reports-distribution': 'Agent Distribution per Shop',
        'reports-shop': 'Shop',
        'reports-total-hours': 'Total Hours',
        'reports-nr-agents': 'Nr. Agents',
        'reports-agents-hours': 'agents',
        'reports-hours-unit': 'hours',
        'reports-select-range': 'Select a date range to generate reports.',
        'reports-no-data': 'No planned data for the selected range.',

        // Charts
        'charts-no-data': 'No productivity data uploaded. Upload files from the Upload section.',
        'charts-hours-unit': 'hours',

        // Edit Modal
        'edit-title': 'Edit Selection',
        'edit-current-selection': 'Current Selection',
        'edit-type-title': 'Edit Type',
        'edit-working-hours': 'Working Hours',
        'edit-working-desc': 'Modify team hour allocation (e.g., 6 IT + 2 HU)',
        'edit-holiday': 'Holiday (CO)',
        'edit-holiday-desc': 'Mark days as holiday',
        'edit-sick': 'Sick Leave (CM)',
        'edit-sick-desc': 'Mark days as sick leave',
        'edit-dayoff': 'Day Off (LB)',
        'edit-dayoff-desc': 'Mark as day off with mandatory justification',
        'edit-legal-holiday': 'Legal Holiday (SL)',
        'edit-legal-holiday-desc': 'Mark days as legal holiday',
        'edit-maternity': 'Maternity Leave (MA)',
        'edit-maternity-desc': 'Mark days as maternity leave',
        'edit-donation': 'Blood Donation (DO)',
        'edit-donation-desc': 'Mark days for blood donation',
        'edit-bereavement': 'Bereavement (DC)',
        'edit-bereavement-desc': 'Mark days for bereavement leave',
        'edit-note-title': 'Notes / Reason',
        'edit-note-placeholder': 'Add a note or reason (optional)...',
        'edit-config-hours': 'Configure Working Hours',
        'edit-total': 'Total:',
        'edit-hours-unit': 'hours',
        'edit-over-limit': 'Exceeds 12 hour limit',
        'edit-dayoff-reason': 'Day Off Justification',
        'edit-dayoff-placeholder': 'Enter the reason for the day off (mandatory)...',
        'edit-cancel': 'Cancel',
        'edit-save': 'Save Changes',
        'edit-select-cells': 'Select at least one cell to edit.',
        'edit-select-type': 'Select an edit type.',
        'edit-over-12': 'Total hours cannot exceed 12 hours per day.',
        'edit-selection': 'Selection:',
        'edit-cells-selected': 'cells selected',
        'edit-total-hours': 'Total hours:',
        'undo-button': 'Undo',
        'undo-nothing': 'Nothing to undo.',
        'undo-confirm': 'Are you sure you want to undo the last change?',
        'undo-success': 'Changes undone!',
        'deactivate-start': 'Start date',
        'deactivate-end': 'End date (optional)',
        'deactivate-end-hint': 'Leave end date empty for indefinite deactivation',
        'deactivate-notes': 'Deactivation reason',
        'deactivate-notes-placeholder': 'Enter the reason for deactivation (optional)...',
        'deactivate-apply': 'Apply',

        // Upload
        'upload-title': 'Upload Files',
        'select-date': '1. Select file date',
        'date-question': 'For which day is the productivity data?',
        'tickets-xlsx': '2. Tickets (XLSX)',
        'calls-csv': '3. Calls (CSV)',
        'drag-xlsx': 'Drag Excel file here or click to select',
        'drag-csv': 'Drag CSV file here or click to select',
        'uploaded-data': 'Uploaded Data',

        // Reports
        'reports-title': 'Reports',

        // Info
        'info-title': 'Information',
        'info-dashboard-title': '1. Dashboard',
        'info-dashboard-desc': 'The main page provides a team overview:',
        'info-dashboard-agents': 'Total Active Agents — the number of agents registered and active in the system',
        'info-dashboard-hours': 'Planned Hours — total planned hours for the current day (Today) or any date selected from the calendar',
        'info-dashboard-teams': 'Hours by Team — the table shows the distribution of hours per team for the selected date',
        'info-dashboard-prod': 'Average Productivity — the average productivity (tickets+calls / hour) over the last days with uploaded data',
        'info-dashboard-trend': 'Productivity Trend — the chart shows productivity per team (tickets+calls / hour) for the entire current month',
        'info-users-title': '2. Users',
        'info-users-desc': 'Manage team agents:',
        'info-users-add': 'Add new agent — fill in the name, username, contract hours, contract type, primary team, and hire date',
        'info-users-inline': 'Inline editing — click directly on any table field to modify it (name, hours, team, etc.)',
        'info-users-team': 'Primary team — the agent\'s main team (e.g., RO zooplus). The agent can also work for other teams as per the planner',
        'info-users-contract': 'Contract Type — Full-time (8h automatic) or Part-time (configurable hours). Changing the contract type opens a modal to select the start date and new hours',
        'info-users-active': 'Active/Inactive — button that opens a modal with options: Indefinite (permanent deactivation) or Period (date range). The planner updates automatically',
        'info-planner-title': '3. Planner',
        'info-planner-desc': 'Monthly work hour planning per agent:',
        'info-planner-format': 'Hours format — enter hours with team code: 8RO = 8 hours on RO, 4RO+4IT = 4 hours RO + 4 hours IT',
        'info-planner-codes': 'Special codes — Co = Holiday, CM = Sick Leave, SL = Legal Holiday, LB = Day Off',
        'info-planner-multi': 'Multi-select — select multiple cells and edit them simultaneously with the edit modal',
        'info-planner-auto': 'Auto-save — all changes are automatically saved to the database',
        'info-prod-title': '4. Productivity',
        'info-prod-desc': 'Productivity analysis based on uploaded data (tickets + calls) and planner hours:',
        'info-prod-period': 'Period selection — choose a date range with the calendar in the top-right corner',
        'info-prod-filter': 'Team filter — select a specific team (e.g., RO, IT) to see only the tickets and calls resolved for that team',
        'info-prod-summary': 'Summary — aggregated view per agent for the entire selected period',
        'info-prod-agent': 'Per Agent — detailed day-by-day view per agent. Select agents using chips or search',
        'info-prod-teams': 'Teams (column) — shows the teams the agent actually worked for, based on uploaded files',
        'info-prod-formula': 'Formula — Productivity = (Tickets + Calls) / Hours Worked',
        'info-upload-title': '5. File Upload',
        'info-upload-desc': 'Upload daily productivity files:',
        'info-upload-step1': 'Step 1: Select date — choose the date for which you\'re uploading data. The system warns if data already exists for that date',
        'info-upload-step2': 'Step 2: XLSX file (Tickets) — upload the Excel file with resolved tickets. The system auto-extracts the agent, ticket count, and team',
        'info-upload-step3': 'Step 3: CSV file (Calls) — upload the CSV file with calls. The system extracts the agent, call count, and team',
        'info-upload-match': 'Auto-matching — names from files are normalized and automatically matched to agents in the system',
        'info-upload-persist': 'Persistence — data is saved to Firebase and persists across sessions',
        'info-reports-title': '6. Reports',
        'info-reports-desc': 'Aggregated reports based on planner data:',
        'info-reports-range': 'Date range selection — choose the desired period with the calendar (default: current month)',
        'info-reports-shop': 'Planned Hours per Shop — table with total planned hours per team and agent count',
        'info-reports-dist': 'Agent Distribution per Shop — cards per team with each agent and their hours, sorted descending',
        'info-ai-title': '7. Sherpa AI',
        'info-ai-desc': 'Integrated AI assistant that can answer questions and perform actions:',
        'info-ai-ask': 'Questions — ask anything about team planning, worked hours, productivity, or team distribution',
        'info-ai-actions': 'Actions — Sherpa AI can modify the schedule, add or delete agents, and navigate between pages',
        'info-ai-safety': 'Safety — destructive actions (deletion) require confirmation. Changes are limited and automatically validated',
        'info-ai-lang': 'Multilingual — responds in the selected language (Romanian, English, Italian)',
        'info-teams-title': 'Team Codes',
        'info-team-ro': 'Romania',
        'info-team-hu': 'Hungary',
        'info-team-it': 'Italy',
        'info-team-nl': 'Netherlands',
        'info-team-cs': 'Czech Republic',
        'info-team-sk': 'Slovakia',
        'info-team-se': 'Sweden',
        'info-team-de': 'Germany',

        // Login
        'login-button': 'Sign in with Google',
        'logout': 'Sign Out',

        // Language names
        'language-romanian': 'Romanian',
        'language-english': 'English',
        'language-italian': 'Italian',

        // Chat
        'chat-welcome': 'Hi! I\'m Sherpa AI. Ask me anything about team planning or request changes.',
        'chat-error': 'Error communicating with AI. Please try again.',
        'chat-invalid-key': 'Invalid API key. Check your settings.',
        'chat-rate-limit': 'Too many requests. Wait a few seconds.',
        'chat-delete-cancelled': 'Deletion cancelled.',

        // Nav items
        'nav-dashboard': 'Dashboard',
        'nav-users': 'Users',
        'nav-planner': 'Planner',
        'nav-productivity': 'Productivity',
        'nav-upload': 'Upload File',
        'nav-reports': 'Reports',
        'nav-logs': 'Logs',
        'nav-roadmap': 'Roadmap',
        'nav-info': 'Info',

        // Logs
        'logs-title': 'Activity Log',
        'logs-loading': 'Loading...',
        'logs-empty': 'No activity recorded.',
        'logs-time': 'Time',
        'logs-user': 'User',
        'logs-type': 'Type',
        'logs-action': 'Action',
        'logs-details': 'Details',
        'logs-filter-all': 'All',
        'logs-refresh': 'Refresh',

        // Roadmap
        'roadmap-title': 'Roadmap',
        'roadmap-bugs-title': 'Known Bugs',
        'roadmap-findings-title': 'Findings & Recommended Improvements',
        'roadmap-future-title': 'Future Development',
        'roadmap-bug-1': 'Gemini API returns 404 on some browsers due to cache — requires Ctrl+Shift+R',
        'roadmap-bug-2': 'API request rate limited without configured Google billing profile',
        'roadmap-bug-3': 'Cross-Origin-Opener-Policy blocks login popup on some browsers',
        'roadmap-bug-4': 'Gemini 3.x "thinking mode" enabled by default causes 400 error with function calling — Fixed',
        'roadmap-bug-5': 'Function response sent as array instead of object — proto serialization error — Fixed',
        'roadmap-bug-6': 'Planner edit actions are not logged in the activity journal',
        'roadmap-finding-1': 'Accessibility — missing ARIA attributes, keyboard navigation, insufficient contrast on secondary text',
        'roadmap-finding-2': 'Performance — planner table generates 2000+ DOM nodes; would benefit from virtualization',
        'roadmap-finding-3': 'Security — Gemini API key is exposed client-side; should be proxied via Cloud Functions',
        'roadmap-finding-4': 'Loading states — missing spinners/skeletons when loading data from Firestore',
        'roadmap-finding-5': 'Data validation — missing schema validation when writing to Firestore',
        'roadmap-finding-6': 'Chat history — lost on page reload (in-memory only)',
        'roadmap-finding-7': 'AI received all data in prompt (10KB+) — migrated to Gemini function calling — Implemented',
        'roadmap-finding-8': 'XSS vulnerability in chat message rendering — Fixed',
        'roadmap-finding-9': 'AI could delete agents without user confirmation — Added confirmation gate',
        'roadmap-future-1': 'Persist chat history in localStorage',
        'roadmap-future-2': 'Export reports to PDF / Excel',
        'roadmap-future-3': 'Push notifications for schedule changes',
        'roadmap-future-4': 'User roles (admin, manager, viewer)',
        'roadmap-future-5': 'Interactive dashboard with charts (drag-and-drop on planner)',
        'roadmap-future-6': 'Calendar integration (Google Calendar sync)',
        'roadmap-future-7': 'Offline mode with sync on reconnect',
        'roadmap-future-8': 'Complete audit trail with version rollback — Implemented',
        'roadmap-future-9': 'Log planner actions (cell edits, agent create/delete) in activity journal',
        'roadmap-future-10': 'Proxy API key via Cloud Functions for security',
        'roadmap-future-11': 'Point-in-Time Restore — automatic planner snapshots saved to Firestore, with the ability to restore team state to any point in time',

        // Form & UI strings
        'create-user-title': 'Create a New User Profile',
        'form-name-placeholder': 'e.g., John Doe',
        'form-username-placeholder': 'e.g., john.doe',
        'form-pt-hours': 'Part-time Hours',
        'form-4h': '4 hours/day',
        'form-5h': '5 hours/day',
        'form-6h': '6 hours/day',
        'form-7h': '7 hours/day',
        'form-8h': '8 hours/day',
        'form-full-time': 'Full-time',
        'form-part-time': 'Part-time',
        'form-create-user': 'Create User',
        'filter-agent': 'Agent',
        'filter-team': 'Team',
        'filter-clear': 'Clear Selections',
        'productivity-trend': 'Productivity Trend - Last 30 Days',
        'no-hours-planned': 'No hours planned for this date.',
        'avg-prod-last-days': 'Last {n} days with data',
        'avg-prod-no-data': 'No productivity data',
        'error-loading-users': 'Error loading users. Data may be stale.',
        'confirm-delete-user': 'Are you sure you want to delete {name}?',
        'fill-required-fields': 'Please fill all required fields.',
        'pt-hours-range': 'Part-time hours must be between 4 and 7.',
        'user-created': '{name} created with {hours}h/{team} schedule.',
        'reactivation-title': 'Reactivation',
        'reactivate-btn': 'Reactivate',
        'agent-reactivated': '{name} has been reactivated.',
        'deactivation-title': 'Deactivation',
        'agent-deactivated': '{name} deactivated: {from} — {to}',
        'contract-updated': 'Contract {name} updated: {type} ({hours}h) from {date}',
        'hours-range-error': 'Contract hours must be between 4 and 8.',
        'hire-date-empty': 'Hire date cannot be empty.',
        'user-updated': 'User updated.',
        'name-empty': 'Full name cannot be empty.',
        'confirm-delete-agent': 'Are you sure you want to delete this agent?',
        'unknown-agent': 'Unknown Agent',
        'error-file-processing': 'Error: {name}',
        'data-overwritten': '"{name}" — data for {date} has been overwritten.',
        'file-processed': '"{name}" processed for {date}!',
        'error-generic': 'Error: {msg}',
    },
    it: {
        // Dashboard
        'dashboard-title': 'Dashboard',
        'total-active-agents': 'Agenti Attivi Totali',
        'agents-in-db': 'Agenti nel database*',
        'planned-hours': 'Ore Pianificate',
        'agents-planned': 'agenti pianificati',
        'average-productivity': 'Produttività Media',
        'today': 'Oggi',
        'tomorrow': 'Domani',
        'hours-by-team': 'Ore Assegnate per Team',
        'hours-by-team-today': 'Ore Assegnate per Team - Oggi',
        'hours-by-team-tomorrow': 'Ore Assegnate per Team - Domani',
        'shop': 'Shop',
        'agents': 'Agenti',
        'total-hours': 'Ore Totali',
        'productivity-trend': 'Trend di Produttività',

        // Users
        'users-title': 'Gestione Utenti',
        'add-new-user': 'Aggiungi Nuovo Utente',
        'full-name': 'Nome Completo',
        'username': 'Nome Utente',
        'contract-hours': 'Ore di Contratto',
        'contract-type': 'Tipo di Contratto',
        'primary-team': 'Team Principale',
        'hire-date': 'Data di Assunzione',
        'active': 'Attivo',
        'inactive': 'Inattivo',
        'actions': 'Azioni',
        'delete': 'Elimina',
        'contract-change-to-pt': 'Cambio a Part-time',
        'contract-change-to-ft': 'Cambio a Full-time',
        'select-start-date': 'Seleziona la data di inizio.',
        'date-must-be-current-month': 'La data deve essere nel mese corrente.',
        'select-start-date-deact': 'Seleziona la data di inizio.',
        'end-date-after-start': 'La data di fine deve essere successiva alla data di inizio.',
        'connecting': 'Connessione...',
        'login-google': 'Accedi con Google',
        'auth-popup-closed': 'La finestra di autenticazione è stata chiusa.',
        'auth-popup-blocked': 'Il popup è stato bloccato. Consenti i popup per questo sito.',
        'auth-cancelled': 'La richiesta di autenticazione è stata annullata.',
        'auth-network-error': 'Errore di rete. Controlla la connessione internet.',
        'auth-unauthorized-domain': 'Dominio non autorizzato. Contatta l\'amministratore.',
        'auth-generic-error': 'Errore di autenticazione. Riprova.',

        // Planner
        'planner-title': 'Pianificatore',
        'search-agent-placeholder': 'Cerca agente...',
        'select-agents': 'Cerca & Seleziona',

        // Productivity
        'productivity-title': 'Produttività',
        'prod-agents-processed': 'Agenti Elaborati',
        'prod-tickets-resolved': 'Ticket Risolti',
        'prod-calls-answered': 'Chiamate Risposte',
        'prod-average': 'Produttività Media',
        'prod-from-xlsx': 'da file XLSX',
        'prod-from-csv': 'da file CSV',
        'prod-formula': '(ticket+chiamate) / ore',
        'prod-days': 'giorni',
        'prod-day': 'giorno',
        'prod-with-data': 'con dati',
        'prod-no-agents': 'Nessun agente trovato. Verifica se il periodo selezionato contiene dati caricati e se gli agenti sono registrati.',
        'prod-upload-to-see': 'Carica i file dalla sezione Upload per vedere i dati.',
        'prod-select-agent': 'Seleziona almeno un agente dalla lista sopra.',
        'prod-no-results': 'Nessun risultato per la selezione corrente.',
        'prod-all-teams': 'Tutti',
        'prod-summary': 'Riepilogo',
        'prod-per-agent': 'Per Agente',
        'prod-all-btn': 'Tutti',
        'prod-none-btn': 'Nessuno',
        'prod-selected': 'selezionati',
        'prod-agents-from-tickets': 'agenti da ticket',
        'prod-agents-from-calls': 'agenti da chiamate',
        'prod-agents-tickets': 'agenti ticket',
        'prod-agents-calls': 'agenti chiamate',
        'prod-no-data-tooltip': 'nessun dato',
        'prod-data-uploaded-for': 'Dati caricati per',
        'prod-can-add-file': 'Puoi aggiungere un altro file o cambiare la data.',
        'prod-date-selected': 'Data selezionata:',
        'prod-can-upload': 'puoi caricare i file.',
        'prod-data-exists': 'esiste già. Il caricamento di nuovi file sovrascriverà i dati esistenti per questo giorno.',
        'prod-data-for': 'I dati per',
        'prod-select-period': 'Seleziona periodo...',
        'prod-search-agent': 'Cerca agente...',
        'prod-save-error': 'Errore nel salvataggio dei dati nel database.',
        'prod-delete-btn': 'Elimina i dati per questo giorno',
        'prod-deleted': 'I dati per {date} sono stati eliminati.',
        'prod-select-date-first': 'Seleziona prima la data dei file!',
        'prod-agents-selected': 'Agenti Selezionati',
        'prod-total-tickets': 'Ticket Totali',
        'prod-total-calls': 'Chiamate Totali',
        'prod-days-with-data': 'giorni con dati',

        // Table headers
        'th-agent': 'Agente',
        'th-teams': 'Team',
        'th-tickets': 'Ticket',
        'th-calls': 'Chiamate',
        'th-total': 'Totale',
        'th-hours-worked': 'Ore Lavorate',
        'th-productivity': 'Produttività',
        'th-date': 'Data',
        'th-schedule': 'Programma',
        'th-hours': 'Ore',

        // Planner
        'planner-agent': 'Agente',
        'planner-hours': 'Ore',
        'planner-total': 'Totale',
        'planner-week-total': 'Tot. Sett.',
        'planner-day-names': 'DOM,LUN,MAR,MER,GIO,VEN,SAB',
        'planner-search-team': 'Cerca team...',
        'planner-search-agent': 'Cerca agente...',
        'planner-select-months': 'Seleziona uno o più mesi da visualizzare.',
        'planner-invalid-range': 'Periodo non valido.',
        'planner-rotate': 'Ruota il telefono in modalità landscape per usare il Pianificatore',
        'edit-btn': 'Modifica',

        // Reports
        'reports-hours-per-shop': 'Ore Pianificate per Shop',
        'reports-distribution': 'Distribuzione Agenti per Shop',
        'reports-shop': 'Shop',
        'reports-total-hours': 'Ore Totali',
        'reports-nr-agents': 'Nr. Agenti',
        'reports-agents-hours': 'agenti',
        'reports-hours-unit': 'ore',
        'reports-select-range': 'Seleziona un intervallo di date per generare i rapporti.',
        'reports-no-data': 'Nessun dato pianificato per l\'intervallo selezionato.',

        // Charts
        'charts-no-data': 'Nessun dato di produttività caricato. Carica i file dalla sezione Upload.',
        'charts-hours-unit': 'ore',

        // Edit Modal
        'edit-title': 'Modifica Selezione',
        'edit-current-selection': 'Selezione Corrente',
        'edit-type-title': 'Tipo di Modifica',
        'edit-working-hours': 'Ore di Lavoro',
        'edit-working-desc': 'Modifica l\'allocazione ore per team (es: 6 IT + 2 HU)',
        'edit-holiday': 'Ferie (CO)',
        'edit-holiday-desc': 'Segna i giorni come ferie',
        'edit-sick': 'Malattia (CM)',
        'edit-sick-desc': 'Segna i giorni come malattia',
        'edit-dayoff': 'Giorno Libero (LB)',
        'edit-dayoff-desc': 'Segna come giorno libero con giustificazione obbligatoria',
        'edit-legal-holiday': 'Festività Legale (SL)',
        'edit-legal-holiday-desc': 'Segna i giorni come festività legale',
        'edit-maternity': 'Congedo Maternità (MA)',
        'edit-maternity-desc': 'Segna i giorni come congedo di maternità',
        'edit-donation': 'Donazione Sangue (DO)',
        'edit-donation-desc': 'Segna i giorni per donazione di sangue',
        'edit-bereavement': 'Lutto (DC)',
        'edit-bereavement-desc': 'Segna i giorni per lutto',
        'edit-note-title': 'Note / Motivo',
        'edit-note-placeholder': 'Aggiungi una nota o motivo (opzionale)...',
        'edit-config-hours': 'Configurazione Ore di Lavoro',
        'edit-total': 'Totale:',
        'edit-hours-unit': 'ore',
        'edit-over-limit': 'Supera il limite di 12 ore',
        'edit-dayoff-reason': 'Giustificazione Giorno Libero',
        'edit-dayoff-placeholder': 'Inserisci il motivo del giorno libero (obbligatorio)...',
        'edit-cancel': 'Annulla',
        'edit-save': 'Salva Modifiche',
        'edit-select-cells': 'Seleziona almeno una cella da modificare.',
        'edit-select-type': 'Seleziona un tipo di modifica.',
        'edit-over-12': 'Il totale delle ore non può superare le 12 ore al giorno.',
        'edit-selection': 'Selezione:',
        'edit-cells-selected': 'celle selezionate',
        'edit-total-hours': 'Ore totali:',
        'undo-button': 'Annulla',
        'undo-nothing': 'Nessuna modifica da annullare.',
        'undo-confirm': 'Sei sicuro di voler annullare l\'ultima modifica?',
        'undo-success': 'Modifiche annullate!',
        'deactivate-start': 'Data di inizio',
        'deactivate-end': 'Data di fine (opzionale)',
        'deactivate-end-hint': 'Lascia la data di fine vuota per disattivazione indefinita',
        'deactivate-notes': 'Motivo disattivazione',
        'deactivate-notes-placeholder': 'Inserisci il motivo della disattivazione (opzionale)...',
        'deactivate-apply': 'Applica',

        // Upload
        'upload-title': 'Caricamento File',
        'select-date': '1. Seleziona la data dei file',
        'date-question': 'Per quale giorno sono i dati di produttività?',
        'tickets-xlsx': '2. Ticket (XLSX)',
        'calls-csv': '3. Chiamate (CSV)',
        'drag-xlsx': 'Trascina il file Excel qui o clicca per selezionare',
        'drag-csv': 'Trascina il file CSV qui o clicca per selezionare',
        'uploaded-data': 'Dati Caricati',

        // Reports
        'reports-title': 'Rapporti',

        // Info
        'info-title': 'Informazioni',
        'info-dashboard-title': '1. Dashboard',
        'info-dashboard-desc': 'La pagina principale offre una panoramica del team:',
        'info-dashboard-agents': 'Totale Agenti Attivi — il numero di agenti registrati e attivi nel sistema',
        'info-dashboard-hours': 'Ore Pianificate — il totale delle ore pianificate per il giorno corrente (Oggi) o qualsiasi data selezionata dal calendario',
        'info-dashboard-teams': 'Ore per Team — la tabella mostra la distribuzione delle ore per team per la data selezionata',
        'info-dashboard-prod': 'Produttività Media — la media della produttività (ticket+chiamate / ora) negli ultimi giorni con dati caricati',
        'info-dashboard-trend': 'Trend Produttività — il grafico mostra la produttività per team (ticket+chiamate / ora) per l\'intero mese corrente',
        'info-users-title': '2. Utenti',
        'info-users-desc': 'Gestione degli agenti del team:',
        'info-users-add': 'Aggiungi nuovo agente — compila nome, username, ore contrattuali, tipo contratto, team primario e data assunzione',
        'info-users-inline': 'Modifica inline — clicca direttamente su qualsiasi campo della tabella per modificarlo (nome, ore, team, ecc.)',
        'info-users-team': 'Team primario — il team principale dell\'agente (es: RO zooplus). L\'agente può lavorare anche per altri team secondo il planner',
        'info-users-contract': 'Tipo Contratto — Full-time (8h automatico) o Part-time (ore configurabili). Cambiare il tipo di contratto apre un modale per selezionare la data di inizio e le nuove ore',
        'info-users-active': 'Attivo/Inattivo — pulsante che apre un modale con opzioni: Indefinito (disattivazione permanente) o Periodo (intervallo date). Il planner si aggiorna automaticamente',
        'info-planner-title': '3. Planner',
        'info-planner-desc': 'Pianificazione mensile delle ore lavorative per agente:',
        'info-planner-format': 'Formato ore — inserisci le ore con il codice team: 8RO = 8 ore su RO, 4RO+4IT = 4 ore RO + 4 ore IT',
        'info-planner-codes': 'Codici speciali — Co = Ferie, CM = Malattia, SL = Festività, LB = Giorno Libero',
        'info-planner-multi': 'Selezione multipla — seleziona più celle e modificale contemporaneamente con il modale di modifica',
        'info-planner-auto': 'Salvataggio automatico — tutte le modifiche vengono salvate automaticamente nel database',
        'info-prod-title': '4. Produttività',
        'info-prod-desc': 'Analisi della produttività basata sui dati caricati (ticket + chiamate) e le ore del planner:',
        'info-prod-period': 'Selezione periodo — scegli un intervallo di date con il calendario nell\'angolo in alto a destra',
        'info-prod-filter': 'Filtro team — seleziona un team specifico (es: RO, IT) per vedere solo i ticket e le chiamate risolti per quel team',
        'info-prod-summary': 'Riepilogo — vista aggregata per agente sull\'intero periodo selezionato',
        'info-prod-agent': 'Per Agente — vista dettagliata giorno per giorno, per agente. Seleziona gli agenti usando i chip o la ricerca',
        'info-prod-teams': 'Team (colonna) — mostra i team per cui l\'agente ha effettivamente lavorato, basato sui file caricati',
        'info-prod-formula': 'Formula — Produttività = (Ticket + Chiamate) / Ore Lavorate',
        'info-upload-title': '5. Carica File',
        'info-upload-desc': 'Caricamento dei file di produttività giornaliera:',
        'info-upload-step1': 'Passo 1: Seleziona data — scegli la data per cui carichi i dati. Il sistema avvisa se esistono già dati per quella data',
        'info-upload-step2': 'Passo 2: File XLSX (Ticket) — carica il file Excel con i ticket risolti. Il sistema estrae automaticamente l\'agente, il numero di ticket e il team',
        'info-upload-step3': 'Passo 3: File CSV (Chiamate) — carica il file CSV con le chiamate. Il sistema estrae l\'agente, il numero di chiamate e il team',
        'info-upload-match': 'Corrispondenza automatica — i nomi dai file vengono normalizzati e abbinati automaticamente agli agenti nel sistema',
        'info-upload-persist': 'Persistenza — i dati vengono salvati su Firebase e persistono tra le sessioni',
        'info-reports-title': '6. Rapporti',
        'info-reports-desc': 'Rapporti aggregati basati sui dati del planner:',
        'info-reports-range': 'Selezione intervallo — scegli il periodo desiderato con il calendario (default: mese corrente)',
        'info-reports-shop': 'Ore Pianificate per Shop — tabella con il totale ore pianificate per team e numero agenti',
        'info-reports-dist': 'Distribuzione Agenti per Shop — schede per team con ogni agente e le sue ore, ordinate in modo decrescente',
        'info-ai-title': '7. Sherpa AI',
        'info-ai-desc': 'Assistente AI integrato che può rispondere a domande ed eseguire azioni:',
        'info-ai-ask': 'Domande — chiedi qualsiasi cosa sulla pianificazione del team, ore lavorate, produttività o distribuzione per team',
        'info-ai-actions': 'Azioni — Sherpa AI può modificare la pianificazione, aggiungere o eliminare agenti e navigare tra le pagine',
        'info-ai-safety': 'Sicurezza — le azioni distruttive (eliminazione) richiedono conferma. Le modifiche sono limitate e validate automaticamente',
        'info-ai-lang': 'Multilingue — risponde nella lingua selezionata (Rumeno, Inglese, Italiano)',
        'info-teams-title': 'Codici Team',
        'info-team-ro': 'Romania',
        'info-team-hu': 'Ungheria',
        'info-team-it': 'Italia',
        'info-team-nl': 'Paesi Bassi',
        'info-team-cs': 'Repubblica Ceca',
        'info-team-sk': 'Slovacchia',
        'info-team-se': 'Svezia',
        'info-team-de': 'Germania',

        // Login
        'login-button': 'Accedi con Google',
        'logout': 'Disconnetti',

        // Language names
        'language-romanian': 'Rumeno',
        'language-english': 'Inglese',
        'language-italian': 'Italiano',

        // Chat
        'chat-welcome': 'Ciao! Sono Sherpa AI. Chiedimi qualsiasi cosa sulla pianificazione del team o richiedi modifiche.',
        'chat-error': 'Errore nella comunicazione con l\'AI. Riprova.',
        'chat-invalid-key': 'Chiave API non valida. Controlla le impostazioni.',
        'chat-rate-limit': 'Troppe richieste. Attendi qualche secondo.',
        'chat-delete-cancelled': 'Eliminazione annullata.',

        // Nav items
        'nav-dashboard': 'Dashboard',
        'nav-users': 'Utenti',
        'nav-planner': 'Pianificatore',
        'nav-productivity': 'Produttività',
        'nav-upload': 'Carica File',
        'nav-reports': 'Rapporti',
        'nav-logs': 'Registro',
        'nav-roadmap': 'Roadmap',
        'nav-info': 'Informazioni',

        // Logs
        'logs-title': 'Registro Attività',
        'logs-loading': 'Caricamento...',
        'logs-empty': 'Nessuna attività registrata.',
        'logs-time': 'Ora',
        'logs-user': 'Utente',
        'logs-type': 'Tipo',
        'logs-action': 'Azione',
        'logs-details': 'Dettagli',
        'logs-filter-all': 'Tutti',
        'logs-refresh': 'Aggiorna',

        // Roadmap
        'roadmap-title': 'Roadmap',
        'roadmap-bugs-title': 'Bug Noti',
        'roadmap-findings-title': 'Osservazioni e Miglioramenti Raccomandati',
        'roadmap-future-title': 'Sviluppi Futuri',
        'roadmap-bug-1': 'Gemini API restituisce 404 su alcuni browser a causa della cache — richiede Ctrl+Shift+R',
        'roadmap-bug-2': 'Tasso di richieste API limitato senza profilo di fatturazione Google configurato',
        'roadmap-bug-3': 'Cross-Origin-Opener-Policy blocca il popup di login su alcuni browser',
        'roadmap-bug-4': 'Gemini 3.x "thinking mode" attivo di default causa errore 400 con function calling — Risolto',
        'roadmap-bug-5': 'Function response inviato come array invece di oggetto — errore proto serialization — Risolto',
        'roadmap-bug-6': 'Le azioni di modifica nel planner non vengono registrate nel diario',
        'roadmap-finding-1': 'Accessibilità — mancano attributi ARIA, navigazione da tastiera, contrasto insufficiente sul testo secondario',
        'roadmap-finding-2': 'Prestazioni — la tabella del planner genera 2000+ nodi DOM; beneficerebbe della virtualizzazione',
        'roadmap-finding-3': 'Sicurezza — la chiave API Gemini è esposta lato client; dovrebbe essere proxata tramite Cloud Functions',
        'roadmap-finding-4': 'Stati di caricamento — mancano spinner/skeleton durante il caricamento dati da Firestore',
        'roadmap-finding-5': 'Validazione dati — manca la validazione dello schema nella scrittura su Firestore',
        'roadmap-finding-6': 'Cronologia chat — si perde al ricaricamento della pagina (solo in memoria)',
        'roadmap-finding-7': 'AI riceveva tutti i dati nel prompt (10KB+) — migrato a Gemini function calling — Implementato',
        'roadmap-finding-8': 'Vulnerabilità XSS nel rendering dei messaggi chat — Risolto',
        'roadmap-finding-9': 'AI poteva eliminare agenti senza conferma utente — Aggiunto gate di conferma',
        'roadmap-future-1': 'Persistenza della cronologia chat in localStorage',
        'roadmap-future-2': 'Esportazione rapporti in PDF / Excel',
        'roadmap-future-3': 'Notifiche push per cambiamenti di programma',
        'roadmap-future-4': 'Ruoli utente (admin, manager, visualizzatore)',
        'roadmap-future-5': 'Dashboard con grafici interattivi (drag-and-drop sul planner)',
        'roadmap-future-6': 'Integrazione calendario (sincronizzazione Google Calendar)',
        'roadmap-future-7': 'Modalità offline con sincronizzazione alla riconnessione',
        'roadmap-future-8': 'Audit trail completo con rollback a versioni precedenti — Implementato',
        'roadmap-future-9': 'Registrazione azioni planner (modifica celle, creazione/eliminazione agenti) nel diario',
        'roadmap-future-10': 'Proxy chiave API tramite Cloud Functions per sicurezza',
        'roadmap-future-11': 'Point-in-Time Restore — salvataggio automatico degli snapshot del planner in Firestore, con possibilità di ripristinare lo stato del team in qualsiasi momento passato',

        // Form & UI strings
        'create-user-title': 'Crea un Nuovo Profilo Utente',
        'form-name-placeholder': 'es: Mario Rossi',
        'form-username-placeholder': 'es: mario.rossi',
        'form-pt-hours': 'Ore Part-time',
        'form-4h': '4 ore/giorno',
        'form-5h': '5 ore/giorno',
        'form-6h': '6 ore/giorno',
        'form-7h': '7 ore/giorno',
        'form-8h': '8 ore/giorno',
        'form-full-time': 'Full-time',
        'form-part-time': 'Part-time',
        'form-create-user': 'Crea Utente',
        'filter-agent': 'Agente',
        'filter-team': 'Team',
        'filter-clear': 'Cancella Selezioni',
        'productivity-trend': 'Trend Produttività - Ultimi 30 Giorni',
        'no-hours-planned': 'Nessuna ora pianificata per questa data.',
        'avg-prod-last-days': 'Ultimi {n} giorni con dati',
        'avg-prod-no-data': 'Nessun dato di produttività',
        'error-loading-users': 'Errore nel caricamento degli utenti.',
        'confirm-delete-user': 'Sei sicuro di voler eliminare {name}?',
        'fill-required-fields': 'Compila tutti i campi obbligatori.',
        'pt-hours-range': 'Le ore part-time devono essere tra 4 e 7.',
        'user-created': '{name} creato con programma {hours}h/{team}.',
        'reactivation-title': 'Riattivazione',
        'reactivate-btn': 'Riattiva',
        'agent-reactivated': '{name} è stato riattivato.',
        'deactivation-title': 'Disattivazione',
        'agent-deactivated': '{name} disattivato: {from} — {to}',
        'contract-updated': 'Contratto {name} aggiornato: {type} ({hours}h) dal {date}',
        'hours-range-error': 'Le ore di contratto devono essere tra 4 e 8.',
        'hire-date-empty': 'La data di assunzione non può essere vuota.',
        'user-updated': 'Utente aggiornato.',
        'name-empty': 'Il nome non può essere vuoto.',
        'confirm-delete-agent': 'Sei sicuro di voler eliminare questo agente?',
        'unknown-agent': 'Agente Sconosciuto',
        'error-file-processing': 'Errore: {name}',
        'data-overwritten': '"{name}" — i dati per {date} sono stati sovrascritti.',
        'file-processed': '"{name}" elaborato per {date}!',
        'error-generic': 'Errore: {msg}',
    }
};

// Charts colors configuration
export const chartColors = {
    primary: '#e8a849',
    secondary: '#9a9590',
    grid: '#2e2e2e',
    text: '#9a9590',
    teams: {
        'RO zooplus': '#e8a849',  // Amber
        'HU zooplus': '#5bb98c',  // Green
        'IT zooplus': '#5b9fe8',  // Blue
        'NL zooplus': '#e8915b',  // Orange
        'CS zooplus': '#b07de8',  // Purple
        'SK zooplus': '#e85b8a',  // Pink
        'SV-SE zooplus': '#5bc8d4' // Cyan
    }
};

// Language configuration
export const languageConfig = {
    ro: { flag: '🇷🇴', name: 'Română', code: 'RO' },
    en: { flag: '🇺🇸', name: 'English', code: 'EN' },
    it: { flag: '🇮🇹', name: 'Italiano', code: 'IT' }
};

// === CENTRALIZED CONSTANTS ===

// Leave/absence codes — single source of truth
export const LEAVE_CODES = ['Co', 'CM', 'LB', 'SL', 'MA', 'DO', 'DC', 'DZ'];

// Check if a schedule value is a non-working code (leave, deactivated, or empty)
export function isNonWorkingCode(value) {
    const trimmed = (value || '').trim();
    return !trimmed || LEAVE_CODES.includes(trimmed);
}

// Normalize team codes for display: SK and CZ merge into CS
export function normalizeTeamForDisplay(code) {
    if (code === 'SK' || code === 'CZ') return 'CS';
    return code;
}

// Parse a single shift entry (e.g. "8RO", "42L", "4CS") into { hours, team }
// Handles team codes starting with digits like "2L" (2nd Level)
export function parseShiftEntry(entry) {
    const p = entry.trim();
    // Try matching team codes that start with a digit (e.g. "42L" = 4h + 2L)
    const match2L = p.match(/^(\d+)(2L)$/i);
    if (match2L) {
        return { hours: parseInt(match2L[1], 10), team: match2L[2].toUpperCase() };
    }
    // Standard: digits followed by optional letters (e.g. "8RO", "4HU", "8")
    const match = p.match(/^(\d+)\s*([A-Za-z-]+)?$/);
    if (match) {
        return { hours: parseInt(match[1], 10), team: match[2] ? match[2].toUpperCase() : null };
    }
    return null;
}

// Extract total hours from a day value string (e.g. "8RO", "42L", "4CS+42L")
export function extractHoursFromDay(dayValue) {
    if (!dayValue || typeof dayValue !== 'string') return 0;
    const trimmed = dayValue.trim();
    if (isNonWorkingCode(trimmed)) return 0;
    let total = 0;
    const parts = trimmed.split('+');
    for (const part of parts) {
        const parsed = parseShiftEntry(part);
        if (parsed) total += parsed.hours;
    }
    return total;
}

// All teams used in the planner allocation UI
export const PLANNER_TEAMS = ['RO', 'HU', 'IT', 'NL', 'CS', 'SK', 'SV-SE', '2L', 'QA', 'TL'];

// Teams used for productivity display (main customer-facing teams)
export const PRODUCTIVITY_TEAMS = ['RO', 'HU', 'IT', 'NL', 'CS', 'SV-SE', 'DE', 'BRO', 'BDE'];

// Valid team codes in uploaded files
export const UPLOAD_VALID_TEAMS = ['RO', 'HU', 'IT', 'NL', 'CS', 'SK', 'SV-SE', 'DE', 'BRO', 'BDE'];

// Team display names for reports
export const TEAM_DISPLAY_NAMES = {
    'RO': 'RO zooplus', 'HU': 'HU zooplus', 'IT': 'IT zooplus',
    'NL': 'NL zooplus', 'CS': 'CS zooplus', 'SK': 'SK zooplus',
    'SV-SE': 'SV-SE zooplus', 'DE': 'DE zooplus', 'BRO': 'BRO zooplus', 'BDE': 'BDE zooplus',
    '2L': '2nd Level', 'QA': 'QA', 'TL': 'Team Lead'
};

// --- Month-keyed data helpers (for multi-month planner support) ---

/** Returns "YYYY-MM" from a Date object */
export function getMonthKey(date) {
    return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}`;
}

/** Returns the days array for a specific month, with backward-compat fallback */
export function getAgentDaysForMonth(agent, monthKey) {
    if (agent.monthlyDays && agent.monthlyDays[monthKey]) {
        return agent.monthlyDays[monthKey];
    }
    return agent.days || [];
}

/** Returns the notes object for a specific month, with backward-compat fallback */
export function getAgentNotesForMonth(agent, monthKey) {
    if (agent.monthlyNotes && agent.monthlyNotes[monthKey]) {
        return agent.monthlyNotes[monthKey];
    }
    return agent.dayNotes || {};
}
