// js/main.js

// --- Core Application Imports ---
import { initializePlanner, cleanupPlanner, clearSelection, undoLastChange } from './planner.js';
import { initializeUsers, cleanupUsers } from './users.js';
import { initializeProductivity, cleanupProductivity } from './productivity.js';
import { initializeReports, cleanupReports } from './reports.js';
import { initializeCharts, initializeProductivityChart } from './charts.js';
import { updateAverageProductivityCard } from './dashboard.js';
import { setTheme, updateLanguageUI, showSection, openEditModal, selectEditType, saveModalChanges, closeEditModal, toggleSidebar } from './ui.js';
import { bindPlannerControlInteractions } from './planner-interaction-wiring.js';
import {
    bindAppLifecycleEvents,
    bindAppRefreshEvents,
    bindAppShellInteractions,
    showAuthenticatedShell,
    showLoginScreen
} from './app-shell-wiring.js';
import { initLogoAnimation } from './logo-animation.js';
import { initializeChat, cleanupChat } from './chat.js';
import { loginWithGoogle, logout, onAuthChange } from './auth.js';
import { initializeLogs, setLogUser, logActivity } from './logs.js';

// --- Dynamic AI Greeting (one per day, generated by Gemini) ---
const GREETING_FALLBACKS = [
    // Index 0=Sunday, 1=Monday, ..., 6=Saturday (matches getDay())
    "Sunday vibes only. You deserve a break! \ud83d\ude0c",
    "It's Monday. Deep breaths, you've got this! \ud83d\udcaa",
    "Tuesday: Monday's chill sister. You're doing great! \ud83c\udf38",
    "Happy Hump Day! Downhill from here! \ud83d\udc2b",
    "Almost Friday... can you feel it? \ud83c\udf89",
    "IT'S FRIDAY! The queen of all days! \ud83d\udc83",
    "Saturday crew = best crew! \ud83d\udcaa",
];

function applyGreeting(message) {
    const loginEl = document.getElementById('loginGreeting');
    const sidebarEl = document.getElementById('sidebarGreeting');
    if (loginEl) loginEl.textContent = message;
    if (sidebarEl) sidebarEl.textContent = message;
}

async function setDynamicGreeting() {
    const today = new Date().toISOString().split('T')[0]; // YYYY-MM-DD

    // Show fallback immediately (will be replaced if AI quote loads)
    const dayOfWeek = new Date().getDay();
    applyGreeting(GREETING_FALLBACKS[dayOfWeek]);

    try {
        const { db } = await import('./firebase-config.js');
        const { doc, getDoc, setDoc } = await import("https://www.gstatic.com/firebasejs/9.6.7/firebase-firestore.js");

        // Check Firestore for today's greeting (shared across all users)
        const greetingDoc = await getDoc(doc(db, 'config', 'daily_greeting'));
        if (greetingDoc.exists()) {
            const data = greetingDoc.data();
            if (data.date === today && data.message) {
                applyGreeting(data.message);
                return; // Today's greeting already exists in DB — done
            }
        }

        // No greeting for today — generate one (first user of the day triggers this)
        const configDoc = await getDoc(doc(db, 'config', 'gemini'));
        if (!configDoc.exists()) return;
        const apiKey = configDoc.data().apiKey;
        if (!apiKey) return;

        const dayNames = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
        const now = new Date();
        const dayName = dayNames[now.getDay()];

        const prompt = `Generate ONE short, fun, uplifting greeting message for a team of women working in customer support (FSP Global / zooplus). Today is ${dayName}. The message should:
- Be warm, witty, and make them smile
- Reference the day of the week naturally
- Be max 12 words + one emoji at the end
- Feel like a supportive friend, not corporate
- Vary in style: sometimes funny, sometimes sweet, sometimes motivational
- Never be generic like "Have a great day"

Reply with ONLY the message, nothing else.`;

        const response = await fetch(
            `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`,
            {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    contents: [{ parts: [{ text: prompt }] }],
                    generationConfig: { temperature: 1.2, maxOutputTokens: 60 }
                })
            }
        );

        if (!response.ok) return;
        const result = await response.json();
        const message = result?.candidates?.[0]?.content?.parts?.[0]?.text?.trim();

        if (message && message.length > 3 && message.length < 100) {
            // Save to Firestore — all users will see the same quote today
            await setDoc(doc(db, 'config', 'daily_greeting'), { date: today, message });
            applyGreeting(message);
        }
    } catch (e) {
        console.log('Greeting fetch skipped:', e.message);
        // Fallback already applied above
    }
}

// --- Global State ---
let currentLanguage = localStorage.getItem('language') || 'ro';
let appInitialized = false;

/**
 * Main application initialization function.
 * This function is the entry point for the application. It sets up the theme,
 * initializes all the main modules (Planner, Users, Dashboard), and sets up
 * the core UI event listeners.
 */
async function initializeApp() {
    if (appInitialized) return; // Prevent double initialization
    appInitialized = true;

    console.log("🚀 Sherpa App Initializing...");

    // Set dynamic greeting message
    setDynamicGreeting();

    // Set theme from local storage or default to 'dark'
    setTheme(localStorage.getItem('theme') || 'dark');

    // Initialize modules that depend on Firestore data
    initializePlanner();
    initializeUsers();
    await initializeProductivity();
    updateAverageProductivityCard(); // Update after productivity data is loaded
    initializeCharts(); // After productivity so chart has real data
    bindAppRefreshEvents({
        eventTarget: document,
        actions: {
            updateAverageProductivityCard,
            initializeProductivityChart
        }
    });
    initializeReports();
    initializeLogs();

    // Initialize core UI elements and event listeners
    bindAppShellInteractions({
        root: document,
        actions: {
            showSection,
            setTheme,
            updateLanguageUI,
            bindPlannerControls: () => bindPlannerControlInteractions({
                root: document,
                documentTarget: document,
                actions: {
                    openEditModal,
                    clearSelection,
                    selectEditType,
                    closeEditModal,
                    saveModalChanges,
                    undoLastChange
                }
            }),
            toggleSidebar,
            logout,
            setAppInitialized: value => { appInitialized = value; }
        },
        getCurrentLanguage: () => currentLanguage,
        setCurrentLanguage: value => { currentLanguage = value; }
    });
    initLogoAnimation();
    await initializeChat();

    console.log("✅ Sherpa App Initialized Successfully.");
}

// --- Lifecycle Event Listeners ---

// Start the authentication flow once the DOM is fully loaded
bindAppLifecycleEvents({
    root: document,
    windowTarget: window,
    storage: localStorage,
    actions: {
        setTheme,
        setDynamicGreeting,
        initLogoAnimation,
        loginWithGoogle,
        onAuthChange,
        onLogin: async (user) => {
            showAuthenticatedShell(user, document);
            setLogUser(user);
            await initializeApp();
            logActivity('auth', 'login', { email: user.email, name: user.displayName || '' });
        },
        onLogout: () => {
            logActivity('auth', 'logout');
            setLogUser(null);
            showLoginScreen(document);
            // Clean up listeners
            cleanupPlanner();
            cleanupUsers();
            cleanupProductivity();
            cleanupReports();
            cleanupChat();
        },
        cleanupBeforeUnload: () => {
            cleanupPlanner();
            cleanupUsers();
            cleanupProductivity();
            cleanupReports();
        }
    }
});
