// js/main.js

// --- Core Application Imports ---
import { initializePlanner, cleanupPlanner, clearSelection, undoLastChange } from './planner.js';
import { initializeUsers, cleanupUsers } from './users.js';
import { initializeProductivity, cleanupProductivity } from './productivity.js';
import { initializeReports, cleanupReports } from './reports.js';
import { initializeCharts } from './charts.js';
import { updateAverageProductivityCard } from './dashboard.js';
import { setTheme, updateLanguageUI, showSection, openEditModal, translatePage, selectEditType, saveModalChanges, closeEditModal, toggleSidebar } from './ui.js';
import { initLogoAnimation } from './logo-animation.js';
import { initializeChat, cleanupChat } from './chat.js';
import { loginWithGoogle, logout, onAuthChange } from './auth.js';
import { initializeLogs, renderLogsSection, setLogUser, logActivity } from './logs.js';

// --- Dynamic AI Greeting (one per day, generated by Gemini) ---
const GREETING_FALLBACKS = [
    // Index 0=Sunday, 1=Monday, ..., 6=Saturday (matches getDay())
    "Sunday vibes only. You deserve a break! \ud83d\ude0c",
    "It's Monday. Deep breaths, you've got this! \ud83d\udcaa",
    "Tuesday: Monday's chill sister. You're doing great! \ud83c\udf38",
    "Happy Hump Day! Downhill from here! \ud83d\udc2b",
    "Almost Friday... can you feel it? \ud83c\udf89",
    "IT'S FRIDAY! The queen of all days! \ud83d\udc83",
    "Saturday crew = best crew! \ud83d\udcaa",
];

function applyGreeting(message) {
    const loginEl = document.getElementById('loginGreeting');
    const sidebarEl = document.getElementById('sidebarGreeting');
    if (loginEl) loginEl.textContent = message;
    if (sidebarEl) sidebarEl.textContent = message;
}

async function setDynamicGreeting() {
    const today = new Date().toISOString().split('T')[0]; // YYYY-MM-DD

    // Show fallback immediately (will be replaced if AI quote loads)
    const dayOfWeek = new Date().getDay();
    applyGreeting(GREETING_FALLBACKS[dayOfWeek]);

    try {
        const { db } = await import('./firebase-config.js');
        const { doc, getDoc, setDoc } = await import("https://www.gstatic.com/firebasejs/9.6.7/firebase-firestore.js");

        // Check Firestore for today's greeting (shared across all users)
        const greetingDoc = await getDoc(doc(db, 'config', 'daily_greeting'));
        if (greetingDoc.exists()) {
            const data = greetingDoc.data();
            if (data.date === today && data.message) {
                applyGreeting(data.message);
                return; // Today's greeting already exists in DB — done
            }
        }

        // No greeting for today — generate one (first user of the day triggers this)
        const configDoc = await getDoc(doc(db, 'config', 'gemini'));
        if (!configDoc.exists()) return;
        const apiKey = configDoc.data().apiKey;
        if (!apiKey) return;

        const dayNames = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
        const now = new Date();
        const dayName = dayNames[now.getDay()];

        const prompt = `Generate ONE short, fun, uplifting greeting message for a team of women working in customer support (FSP Global / zooplus). Today is ${dayName}. The message should:
- Be warm, witty, and make them smile
- Reference the day of the week naturally
- Be max 12 words + one emoji at the end
- Feel like a supportive friend, not corporate
- Vary in style: sometimes funny, sometimes sweet, sometimes motivational
- Never be generic like "Have a great day"

Reply with ONLY the message, nothing else.`;

        const response = await fetch(
            `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${apiKey}`,
            {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    contents: [{ parts: [{ text: prompt }] }],
                    generationConfig: { temperature: 1.2, maxOutputTokens: 60 }
                })
            }
        );

        if (!response.ok) return;
        const result = await response.json();
        const message = result?.candidates?.[0]?.content?.parts?.[0]?.text?.trim();

        if (message && message.length > 3 && message.length < 100) {
            // Save to Firestore — all users will see the same quote today
            await setDoc(doc(db, 'config', 'daily_greeting'), { date: today, message });
            applyGreeting(message);
        }
    } catch (e) {
        console.log('Greeting fetch skipped:', e.message);
        // Fallback already applied above
    }
}

// --- Global State ---
let currentLanguage = localStorage.getItem('language') || 'ro';
let appInitialized = false;

/**
 * Main application initialization function.
 * This function is the entry point for the application. It sets up the theme,
 * initializes all the main modules (Planner, Users, Dashboard), and sets up
 * the core UI event listeners.
 */
async function initializeApp() {
    if (appInitialized) return; // Prevent double initialization
    appInitialized = true;

    console.log("🚀 Sherpa App Initializing...");

    // Set dynamic greeting message
    setDynamicGreeting();

    // Set theme from local storage or default to 'dark'
    setTheme(localStorage.getItem('theme') || 'dark');

    // Initialize modules that depend on Firestore data
    initializePlanner();
    initializeUsers();
    await initializeProductivity();
    updateAverageProductivityCard(); // Update after productivity data is loaded
    initializeCharts(); // After productivity so chart has real data
    initializeReports();
    initializeLogs();

    // Initialize core UI elements and event listeners
    initializeUI();
    initLogoAnimation();
    await initializeChat();

    console.log("✅ Sherpa App Initialized Successfully.");
}

/**
 * Show login screen, hide app
 */
function showLoginScreen() {
    const loginScreen = document.getElementById('loginScreen');
    const appContainer = document.getElementById('appContainer');
    if (loginScreen) loginScreen.style.display = 'flex';
    if (appContainer) appContainer.style.display = 'none';
}

/**
 * Show app, hide login screen, and populate user info
 */
function showApp(user) {
    const loginScreen = document.getElementById('loginScreen');
    const appContainer = document.getElementById('appContainer');
    if (loginScreen) loginScreen.style.display = 'none';
    if (appContainer) appContainer.style.display = '';

    // Update sidebar user info
    const avatar = document.getElementById('userAvatar');
    const userName = document.getElementById('userName');
    const userEmail = document.getElementById('userEmail');
    if (avatar) {
        avatar.src = user.photoURL || '';
        avatar.style.display = user.photoURL ? 'block' : 'none';
    }
    if (userName) userName.textContent = user.displayName || 'User';
    if (userEmail) userEmail.textContent = user.email || '';
}

/**
 * Sets up core UI event listeners for navigation, theme toggling,
 * and language selection.
 */
function initializeUI() {
    // Navigation menu
    const navItems = document.querySelectorAll('.nav-item');
    navItems.forEach(item => {
        item.addEventListener('click', () => {
            const sectionId = item.dataset.tooltip;
            showSection(sectionId, item);
        });
    });

    // Theme toggle button
    const themeToggle = document.querySelector('.theme-toggle');
    if (themeToggle) {
        themeToggle.addEventListener('click', () => {
            const current = document.documentElement.getAttribute('data-theme') || 'dark';
            const newTheme = current === 'dark' ? 'light' : 'dark';
            setTheme(newTheme);
        });
    }

    // Language selector dropdown
    const languageDropdown = document.querySelector('.language-dropdown');
    const languageMenu = document.getElementById('languageMenu');
    if (languageDropdown) {
        languageDropdown.addEventListener('click', (e) => {
            e.stopPropagation();
            languageMenu.classList.toggle('open');
            languageDropdown.classList.toggle('open');
        });
    }
    if (languageMenu) {
        languageMenu.addEventListener('click', (e) => {
            const target = e.target.closest('.language-option');
            if (target) {
                currentLanguage = target.dataset.lang;
                updateLanguageUI(currentLanguage);
                languageMenu.classList.remove('open');
                languageDropdown.classList.remove('open');
            }
        });
    }

    // Initial translation — full UI update (flag, active option, all text)
    updateLanguageUI(currentLanguage);
    // Selection counter buttons
    const editBtn = document.getElementById('editSelectionBtn');
    if (editBtn) {
        editBtn.addEventListener('click', openEditModal);
    }
    const cancelBtn = document.getElementById('cancelSelectionBtn');
    if (cancelBtn) {
        cancelBtn.addEventListener('click', clearSelection);
    }

    // Modal event listeners
    document.querySelectorAll('.edit-option').forEach(option => {
        option.addEventListener('click', () => selectEditType(option.dataset.type));
    });
    const closeModalBtn = document.querySelector('.edit-modal-close');
    if (closeModalBtn) {
        closeModalBtn.addEventListener('click', closeEditModal);
    }
    const saveBtn = document.getElementById('saveButton');
    if (saveBtn) {
        saveBtn.addEventListener('click', saveModalChanges);
    }
    const cancelModalBtn = document.querySelector('.edit-actions .btn-secondary');
    if (cancelModalBtn) {
        cancelModalBtn.addEventListener('click', closeEditModal);
    }

    // Undo button
    const undoBtn = document.getElementById('undoBtn');
    if (undoBtn) {
        undoBtn.style.display = 'inline-flex';
        undoBtn.addEventListener('click', undoLastChange);
    }
    // Ctrl+Z keyboard shortcut for undo (when not in an input/textarea)
    document.addEventListener('keydown', (e) => {
        if ((e.ctrlKey || e.metaKey) && e.key === 'z' && !e.target.matches('input, textarea, [contenteditable]')) {
            e.preventDefault();
            undoLastChange();
        }
    });

    // Sidebar toggle
    const sidebarToggle = document.querySelector('.sidebar-toggle');
    if (sidebarToggle) {
        sidebarToggle.addEventListener('click', toggleSidebar);
    }

    // Logout button
    const logoutBtn = document.getElementById('logoutBtn');
    if (logoutBtn) {
        logoutBtn.addEventListener('click', async () => {
            await logout();
            appInitialized = false;
        });
    }
}

// --- Lifecycle Event Listeners ---

// Start the authentication flow once the DOM is fully loaded
document.addEventListener('DOMContentLoaded', () => {
    // Set theme immediately so login screen looks correct
    setTheme(localStorage.getItem('theme') || 'dark');

    // Set dynamic greeting on login screen
    setDynamicGreeting();

    // Init login screen logo animation
    initLogoAnimation('loginLogo', 100);

    // Set up Google login button
    const googleLoginBtn = document.getElementById('googleLoginBtn');
    if (googleLoginBtn) {
        googleLoginBtn.addEventListener('click', loginWithGoogle);
    }

    // Listen for auth state changes
    onAuthChange(
        // On login
        async (user) => {
            showApp(user);
            setLogUser(user);
            await initializeApp();
            logActivity('auth', 'login', { email: user.email, name: user.displayName || '' });
        },
        // On logout
        () => {
            logActivity('auth', 'logout');
            setLogUser(null);
            showLoginScreen();
            // Clean up listeners
            cleanupPlanner();
            cleanupUsers();
            cleanupProductivity();
            cleanupReports();
            cleanupChat();
        }
    );
});

// Clean up Firestore listeners when the user leaves the page to prevent memory leaks
window.addEventListener('beforeunload', () => {
    cleanupPlanner();
    cleanupUsers();
    cleanupProductivity();
    cleanupReports();
}); 